### ISSUE TITLE
message = "undefined is not a function (evaluating 'Ti.App.iOS.createSearchableIndex()')";

### ISSUE THREAD

**Issue by sobytes** [appcelerator-developer-relations/appc-sample-appsearch#1]
Hi 

When i try to run the app i get .

```
message = "undefined is not a function (evaluating 'Ti.App.iOS.createSearchableIndex()')";
```

I have the latest sdk 5.0?

**Comment by FokkeZB** [comment]
Could you share your build logs?

**Comment by kopiro** [comment]
Same here

**Comment by FokkeZB** [comment]
Could you maybe share your build logs? Do you have LiveView enabled?

**Comment by kopiro** [comment]
I'm building with TiShadow, maybe I'll try without first.

**Comment by sobytes** [comment]
I am pretty sure my issue was because i was running a old version i updated everything and it worked fine for me in the end.

**Comment by kopiro** [comment]
Yes, it seems TiShadow.

**Comment by FokkeZB** [comment]
Yep, this file needs to be updated:
https://github.com/dbankier/TiShadow/blob/master/app/Resources/api/Includes.js

**Comment by kopiro** [comment]
Made a PR ;)
https://github.com/dbankier/TiShadow/pull/470
